### ISSUE TITLE
Horari diumenge

### ISSUE THREAD

**Issue by ckrina** [Drupalcat/drupalsummerbarcelona#29]
A redactar text en EN/ES/CA
- De 9 a 14h
- Obert a tothom
- Si hi ha quorum es farà sessió d'intro a contrib per instal·lar eines i conèixer issue queue i com es fan parches

**Comment by mireia-omada** [comment]
@ckrina estava fent una plana de horari com els altres dies però crec que no és el que tenies en ment.
Hem pots orientar un mica? Thanks!

![screen shot 2016-07-07 at 19 47 18](https://cloud.githubusercontent.com/assets/1492469/16663263/c6d2594c-447b-11e6-8cb3-94d625d84399.png)

**Comment by ckrina** [comment]
@mireia-omada doncs si que anava per aqui! Potser es pot fer la sessió de mentoring de 1 hora (en realitat dependrà de si hi ha gent o no) per a que tingui sentit fer 2 columnes, i després de la sessió de mentoring es pot posar que hi haurà mentored sprints i així s'omple l'altra fila. Què et sembla?
![c6d2594c-447b-11e6-8cb3-94d625d84399](https://cloud.githubusercontent.com/assets/2225966/16667004/74ec2b62-448a-11e6-808f-9a63594d17b3.png)
